name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.6.6
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0
  provider: ^6.0.0
  pie_chart: ^5.4.0
  shared_preferences: ^2.1.0

  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.4.1
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  http: ^1.2.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/page1.jpg
  