name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.4.1
  image_picker: ^0.8.5+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/page1.jpg
   
